"""Add slug to Post

Revision ID: 115913f19ba0
Revises: afeda67a17f9
Create Date: 2025-10-15 10:57:58.195244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115913f19ba0'
down_revision = 'afeda67a17f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
