"""Add public id a to Post

Revision ID: 5b0d226a4363
Revises: 115913f19ba0
Create Date: 2025-10-19 09:17:17.781761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0d226a4363'
down_revision = '115913f19ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_image_public_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('featured_image_public_id')

    # ### end Alembic commands ###
